// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM2JcQgRk6QuYG6Lq8J3oTYQ5U7Mxm-Xc',
    appId: '1:94853445995:web:b1398abb6d3945239bb42e',
    messagingSenderId: '94853445995',
    projectId: 'fashion51',
    authDomain: 'fashion51.firebaseapp.com',
    storageBucket: 'fashion51.firebasestorage.app',
    measurementId: 'G-LMBD4VCBLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Ig8v5pvydT1J02Kd6r4WteV4sZv8mAI',
    appId: '1:94853445995:android:99dcce19ac51c0e49bb42e',
    messagingSenderId: '94853445995',
    projectId: 'fashion51',
    storageBucket: 'fashion51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGdZ7XPtBBZiEmUw6JJ_UQ7Oz20r-hfI',
    appId: '1:94853445995:ios:85d6b04153d515b09bb42e',
    messagingSenderId: '94853445995',
    projectId: 'fashion51',
    storageBucket: 'fashion51.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGdZ7XPtBBZiEmUw6JJ_UQ7Oz20r-hfI',
    appId: '1:94853445995:ios:85d6b04153d515b09bb42e',
    messagingSenderId: '94853445995',
    projectId: 'fashion51',
    storageBucket: 'fashion51.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM2JcQgRk6QuYG6Lq8J3oTYQ5U7Mxm-Xc',
    appId: '1:94853445995:web:e1673c18bca55f529bb42e',
    messagingSenderId: '94853445995',
    projectId: 'fashion51',
    authDomain: 'fashion51.firebaseapp.com',
    storageBucket: 'fashion51.firebasestorage.app',
    measurementId: 'G-E32YNXPW8D',
  );
}
